# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@1
  displayName: 'Install dotnet core 3.0 (preview)'
  inputs:
    includePreviewVersions: true
    version: '3.0.100-preview8-013656'
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- script: dotnet build -c Release

- script: dotnet run --project tests/DotNetLightning.Tests
- script: dotnet run --project tests/DotNetLightning.Infrastructure.Tests
