/// This file was automatically generated using following command:
/// ```bash
/// msggen
/// ```
///
/// Do not edit this file, it'll be overwritten. Rather edit the schema that
/// This file was generated from
namespace DotNetLightning.ClnRpc.Tests


open Xunit
open FsCheck
open FsCheck.Xunit
open DotNetLightning.ClnRpc
open Generators

type SerializationTests() =
    do
        Arb.register<PrimitiveGenerators>() |> ignore
        Arb.register<NonNullOptionGenerator>() |> ignore

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.GetinfoRequest(v: Requests.GetinfoRequest) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.GetinfoResponse(v: Responses.GetinfoResponse) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.ListpeersRequest(v: Requests.ListpeersRequest) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.ListpeersResponse(v: Responses.ListpeersResponse) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.ListfundsRequest(v: Requests.ListfundsRequest) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.ListfundsResponse(v: Responses.ListfundsResponse) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.SendpayRequest(v: Requests.SendpayRequest) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.SendpayResponse(v: Responses.SendpayResponse) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.ListchannelsRequest(v: Requests.ListchannelsRequest) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.ListchannelsResponse(v: Responses.ListchannelsResponse) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.AddgossipRequest(v: Requests.AddgossipRequest) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.AddgossipResponse(v: Responses.AddgossipResponse) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.AutocleaninvoiceRequest(v: Requests.AutocleaninvoiceRequest) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.AutocleaninvoiceResponse
        (v: Responses.AutocleaninvoiceResponse)
        =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.CheckmessageRequest(v: Requests.CheckmessageRequest) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.CheckmessageResponse(v: Responses.CheckmessageResponse) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.CloseRequest(v: Requests.CloseRequest) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.CloseResponse(v: Responses.CloseResponse) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.ConnectRequest(v: Requests.ConnectRequest) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.ConnectResponse(v: Responses.ConnectResponse) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.CreateinvoiceRequest(v: Requests.CreateinvoiceRequest) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.CreateinvoiceResponse(v: Responses.CreateinvoiceResponse) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.DatastoreRequest(v: Requests.DatastoreRequest) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.DatastoreResponse(v: Responses.DatastoreResponse) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.CreateonionRequest(v: Requests.CreateonionRequest) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.CreateonionResponse(v: Responses.CreateonionResponse) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.DeldatastoreRequest(v: Requests.DeldatastoreRequest) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.DeldatastoreResponse(v: Responses.DeldatastoreResponse) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.DelexpiredinvoiceRequest(v: Requests.DelexpiredinvoiceRequest) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.DelexpiredinvoiceResponse
        (v: Responses.DelexpiredinvoiceResponse)
        =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.DelinvoiceRequest(v: Requests.DelinvoiceRequest) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.DelinvoiceResponse(v: Responses.DelinvoiceResponse) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.InvoiceRequest(v: Requests.InvoiceRequest) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.InvoiceResponse(v: Responses.InvoiceResponse) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.ListdatastoreRequest(v: Requests.ListdatastoreRequest) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.ListdatastoreResponse(v: Responses.ListdatastoreResponse) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.ListinvoicesRequest(v: Requests.ListinvoicesRequest) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.ListinvoicesResponse(v: Responses.ListinvoicesResponse) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.SendonionRequest(v: Requests.SendonionRequest) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.SendonionResponse(v: Responses.SendonionResponse) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.ListsendpaysRequest(v: Requests.ListsendpaysRequest) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.ListsendpaysResponse(v: Responses.ListsendpaysResponse) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.ListtransactionsRequest(v: Requests.ListtransactionsRequest) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.ListtransactionsResponse
        (v: Responses.ListtransactionsResponse)
        =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.PayRequest(v: Requests.PayRequest) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.PayResponse(v: Responses.PayResponse) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.ListnodesRequest(v: Requests.ListnodesRequest) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.ListnodesResponse(v: Responses.ListnodesResponse) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.WaitanyinvoiceRequest(v: Requests.WaitanyinvoiceRequest) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.WaitanyinvoiceResponse(v: Responses.WaitanyinvoiceResponse) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.WaitinvoiceRequest(v: Requests.WaitinvoiceRequest) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.WaitinvoiceResponse(v: Responses.WaitinvoiceResponse) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.WaitsendpayRequest(v: Requests.WaitsendpayRequest) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.WaitsendpayResponse(v: Responses.WaitsendpayResponse) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.NewaddrRequest(v: Requests.NewaddrRequest) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.NewaddrResponse(v: Responses.NewaddrResponse) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.WithdrawRequest(v: Requests.WithdrawRequest) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.WithdrawResponse(v: Responses.WithdrawResponse) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.KeysendRequest(v: Requests.KeysendRequest) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.KeysendResponse(v: Responses.KeysendResponse) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.FundpsbtRequest(v: Requests.FundpsbtRequest) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.FundpsbtResponse(v: Responses.FundpsbtResponse) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.SendpsbtRequest(v: Requests.SendpsbtRequest) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.SendpsbtResponse(v: Responses.SendpsbtResponse) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.SignpsbtRequest(v: Requests.SignpsbtRequest) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.SignpsbtResponse(v: Responses.SignpsbtResponse) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.UtxopsbtRequest(v: Requests.UtxopsbtRequest) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.UtxopsbtResponse(v: Responses.UtxopsbtResponse) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.TxdiscardRequest(v: Requests.TxdiscardRequest) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.TxdiscardResponse(v: Responses.TxdiscardResponse) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.TxprepareRequest(v: Requests.TxprepareRequest) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.TxprepareResponse(v: Responses.TxprepareResponse) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.TxsendRequest(v: Requests.TxsendRequest) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.TxsendResponse(v: Responses.TxsendResponse) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.DisconnectRequest(v: Requests.DisconnectRequest) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.DisconnectResponse(v: Responses.DisconnectResponse) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.FeeratesRequest(v: Requests.FeeratesRequest) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.FeeratesResponse(v: Responses.FeeratesResponse) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.GetrouteRequest(v: Requests.GetrouteRequest) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.GetrouteResponse(v: Responses.GetrouteResponse) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.ListforwardsRequest(v: Requests.ListforwardsRequest) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.ListforwardsResponse(v: Responses.ListforwardsResponse) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.ListpaysRequest(v: Requests.ListpaysRequest) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.ListpaysResponse(v: Responses.ListpaysResponse) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.PingRequest(v: Requests.PingRequest) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.PingResponse(v: Responses.PingResponse) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.SignmessageRequest(v: Requests.SignmessageRequest) =
        serializationTestRoundtrip<_> v

    [<Property>]
    [<Trait("PropTest", "PropTest")>]
    member this.SignmessageResponse(v: Responses.SignmessageResponse) =
        serializationTestRoundtrip<_> v
